"""empty message

Revision ID: 069712353066
Revises: af684d0bf824
Create Date: 2020-01-28 01:15:37.938556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069712353066'
down_revision = 'af684d0bf824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(length=140), nullable=True),
    sa.Column('super_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_name'], ['image.folder_name'], ),
    sa.ForeignKeyConstraint(['super_id'], ['superclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
